name: CI/CD for NestJS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Archive production artifacts
      run: tar -czvf nestjs-app.tar.gz .
      continue-on-error: true

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: nestjs-app
        path: nestjs-app.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: nestjs-app
        path: .

    - name: Deploy to EC2
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region ${{ secrets.AWS_REGION }}

        # Copy the artifact to the EC2 instance
        scp -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no nestjs-app.tar.gz ec2-user@${{ secrets.EC2_PUBLIC_DNS }}:~/

        # Connect to EC2 instance and deploy
        ssh -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
          pm2 stop all || true
          rm -rf ~/nestjs-app
          mkdir ~/nestjs-app
          tar -xzvf ~/nestjs-app.tar.gz -C ~/nestjs-app
          cd ~/nestjs-app
          npm install --production
          pm2 start dist/main.js
EOF
