name: CI/CD - Next.js on AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build Next.js app
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    environment:
      name: prod
      secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to EC2
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-keygen -i /tmp/ssh-key -f /tmp/ssh-key
          chmod 600 /tmp/ssh-key
          scp -i /tmp/ssh-key -o StrictHostKeyChecking=no ./build/* ec2-user@3.87.95.221:/typescript-starter
